// API
const API_URL = "https://api.example.com";

// Queries
const GET_QUERY = ["GET_NOUN_IN_PLURAL"];

const MUTATION_INSERT_QUERY = ["MUTATION_INSERT_NOUN_IN_PLURAL"];

const MUTATION_PATCH_QUERY = ["MUTATION_PATCH_NOUN_IN_PLURAL"];

const MUTATION_DELETE_QUERY = ["MUTATION_DELETE_NOUN_IN_PLURAL"];

export {
  API_URL,
  GET_QUERY,
  MUTATION_INSERT_QUERY,
  MUTATION_PATCH_QUERY,
  MUTATION_DELETE_QUERY,
};
